# Generated by Django 4.0.3 on 2023-03-13 14:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvtapp', '0003_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(default=datetime.datetime(2023, 3, 13, 14, 34, 23, 896737, tzinfo=utc), upload_to=''),
        ),
    ]
