# Generated by Django 4.0.3 on 2023-03-13 14:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mvtapp', '0004_alter_staff_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_start_year', models.DateField()),
                ('session_end_year', models.DateField()),
            ],
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='staff',
            name='profile_pic',
            field=models.FileField(default=datetime.datetime(2023, 3, 13, 14, 36, 14, 125956, tzinfo=utc), upload_to=''),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvtapp.sessionyearmodel'),
        ),
        migrations.AddField(
            model_name='student',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvtapp.sessionyearmodel'),
        ),
        migrations.AddField(
            model_name='termdetails',
            name='session_year_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mvtapp.sessionyearmodel'),
        ),
    ]
